// Generated by gencpp from file displayImage/imageName.msg
// DO NOT EDIT!


#ifndef DISPLAYIMAGE_MESSAGE_IMAGENAME_H
#define DISPLAYIMAGE_MESSAGE_IMAGENAME_H

#include <ros/service_traits.h>


#include <displayImage/imageNameRequest.h>
#include <displayImage/imageNameResponse.h>


namespace displayImage
{

struct imageName
{

typedef imageNameRequest Request;
typedef imageNameResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct imageName
} // namespace displayImage


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::displayImage::imageName > {
  static const char* value()
  {
    return "72eb6ddb2879109c337866e5e016a815";
  }

  static const char* value(const ::displayImage::imageName&) { return value(); }
};

template<>
struct DataType< ::displayImage::imageName > {
  static const char* value()
  {
    return "displayImage/imageName";
  }

  static const char* value(const ::displayImage::imageName&) { return value(); }
};


// service_traits::MD5Sum< ::displayImage::imageNameRequest> should match
// service_traits::MD5Sum< ::displayImage::imageName >
template<>
struct MD5Sum< ::displayImage::imageNameRequest>
{
  static const char* value()
  {
    return MD5Sum< ::displayImage::imageName >::value();
  }
  static const char* value(const ::displayImage::imageNameRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::displayImage::imageNameRequest> should match
// service_traits::DataType< ::displayImage::imageName >
template<>
struct DataType< ::displayImage::imageNameRequest>
{
  static const char* value()
  {
    return DataType< ::displayImage::imageName >::value();
  }
  static const char* value(const ::displayImage::imageNameRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::displayImage::imageNameResponse> should match
// service_traits::MD5Sum< ::displayImage::imageName >
template<>
struct MD5Sum< ::displayImage::imageNameResponse>
{
  static const char* value()
  {
    return MD5Sum< ::displayImage::imageName >::value();
  }
  static const char* value(const ::displayImage::imageNameResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::displayImage::imageNameResponse> should match
// service_traits::DataType< ::displayImage::imageName >
template<>
struct DataType< ::displayImage::imageNameResponse>
{
  static const char* value()
  {
    return DataType< ::displayImage::imageName >::value();
  }
  static const char* value(const ::displayImage::imageNameResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DISPLAYIMAGE_MESSAGE_IMAGENAME_H
