// Generated by gencpp from file displayImage/imageNameResponse.msg
// DO NOT EDIT!


#ifndef DISPLAYIMAGE_MESSAGE_IMAGENAMERESPONSE_H
#define DISPLAYIMAGE_MESSAGE_IMAGENAMERESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace displayImage
{
template <class ContainerAllocator>
struct imageNameResponse_
{
  typedef imageNameResponse_<ContainerAllocator> Type;

  imageNameResponse_()
    : sum(0)  {
    }
  imageNameResponse_(const ContainerAllocator& _alloc)
    : sum(0)  {
  (void)_alloc;
    }



   typedef int64_t _sum_type;
  _sum_type sum;





  typedef boost::shared_ptr< ::displayImage::imageNameResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::displayImage::imageNameResponse_<ContainerAllocator> const> ConstPtr;

}; // struct imageNameResponse_

typedef ::displayImage::imageNameResponse_<std::allocator<void> > imageNameResponse;

typedef boost::shared_ptr< ::displayImage::imageNameResponse > imageNameResponsePtr;
typedef boost::shared_ptr< ::displayImage::imageNameResponse const> imageNameResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::displayImage::imageNameResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::displayImage::imageNameResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::displayImage::imageNameResponse_<ContainerAllocator1> & lhs, const ::displayImage::imageNameResponse_<ContainerAllocator2> & rhs)
{
  return lhs.sum == rhs.sum;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::displayImage::imageNameResponse_<ContainerAllocator1> & lhs, const ::displayImage::imageNameResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace displayImage

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::displayImage::imageNameResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::displayImage::imageNameResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::displayImage::imageNameResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::displayImage::imageNameResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::displayImage::imageNameResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::displayImage::imageNameResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::displayImage::imageNameResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b88405221c77b1878a3cbbfff53428d7";
  }

  static const char* value(const ::displayImage::imageNameResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb88405221c77b187ULL;
  static const uint64_t static_value2 = 0x8a3cbbfff53428d7ULL;
};

template<class ContainerAllocator>
struct DataType< ::displayImage::imageNameResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "displayImage/imageNameResponse";
  }

  static const char* value(const ::displayImage::imageNameResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::displayImage::imageNameResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64 sum\n"
"\n"
;
  }

  static const char* value(const ::displayImage::imageNameResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::displayImage::imageNameResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.sum);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct imageNameResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::displayImage::imageNameResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::displayImage::imageNameResponse_<ContainerAllocator>& v)
  {
    s << indent << "sum: ";
    Printer<int64_t>::stream(s, indent + "  ", v.sum);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DISPLAYIMAGE_MESSAGE_IMAGENAMERESPONSE_H
