// Generated by gencpp from file displayImage/motorRequest.msg
// DO NOT EDIT!


#ifndef DISPLAYIMAGE_MESSAGE_MOTORREQUEST_H
#define DISPLAYIMAGE_MESSAGE_MOTORREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace displayImage
{
template <class ContainerAllocator>
struct motorRequest_
{
  typedef motorRequest_<ContainerAllocator> Type;

  motorRequest_()
    : a(0)
    , b(0)
    , c(0)
    , d(0)
    , e(0)
    , f(0)  {
    }
  motorRequest_(const ContainerAllocator& _alloc)
    : a(0)
    , b(0)
    , c(0)
    , d(0)
    , e(0)
    , f(0)  {
  (void)_alloc;
    }



   typedef int64_t _a_type;
  _a_type a;

   typedef int64_t _b_type;
  _b_type b;

   typedef int64_t _c_type;
  _c_type c;

   typedef int64_t _d_type;
  _d_type d;

   typedef int64_t _e_type;
  _e_type e;

   typedef int64_t _f_type;
  _f_type f;





  typedef boost::shared_ptr< ::displayImage::motorRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::displayImage::motorRequest_<ContainerAllocator> const> ConstPtr;

}; // struct motorRequest_

typedef ::displayImage::motorRequest_<std::allocator<void> > motorRequest;

typedef boost::shared_ptr< ::displayImage::motorRequest > motorRequestPtr;
typedef boost::shared_ptr< ::displayImage::motorRequest const> motorRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::displayImage::motorRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::displayImage::motorRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::displayImage::motorRequest_<ContainerAllocator1> & lhs, const ::displayImage::motorRequest_<ContainerAllocator2> & rhs)
{
  return lhs.a == rhs.a &&
    lhs.b == rhs.b &&
    lhs.c == rhs.c &&
    lhs.d == rhs.d &&
    lhs.e == rhs.e &&
    lhs.f == rhs.f;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::displayImage::motorRequest_<ContainerAllocator1> & lhs, const ::displayImage::motorRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace displayImage

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::displayImage::motorRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::displayImage::motorRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::displayImage::motorRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::displayImage::motorRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::displayImage::motorRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::displayImage::motorRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::displayImage::motorRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "44df49721ed7faf4a1aaf2bb88b86d56";
  }

  static const char* value(const ::displayImage::motorRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x44df49721ed7faf4ULL;
  static const uint64_t static_value2 = 0xa1aaf2bb88b86d56ULL;
};

template<class ContainerAllocator>
struct DataType< ::displayImage::motorRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "displayImage/motorRequest";
  }

  static const char* value(const ::displayImage::motorRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::displayImage::motorRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64 a\n"
"int64 b\n"
"int64 c\n"
"int64 d\n"
"int64 e\n"
"int64 f\n"
;
  }

  static const char* value(const ::displayImage::motorRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::displayImage::motorRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.a);
      stream.next(m.b);
      stream.next(m.c);
      stream.next(m.d);
      stream.next(m.e);
      stream.next(m.f);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct motorRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::displayImage::motorRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::displayImage::motorRequest_<ContainerAllocator>& v)
  {
    s << indent << "a: ";
    Printer<int64_t>::stream(s, indent + "  ", v.a);
    s << indent << "b: ";
    Printer<int64_t>::stream(s, indent + "  ", v.b);
    s << indent << "c: ";
    Printer<int64_t>::stream(s, indent + "  ", v.c);
    s << indent << "d: ";
    Printer<int64_t>::stream(s, indent + "  ", v.d);
    s << indent << "e: ";
    Printer<int64_t>::stream(s, indent + "  ", v.e);
    s << indent << "f: ";
    Printer<int64_t>::stream(s, indent + "  ", v.f);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DISPLAYIMAGE_MESSAGE_MOTORREQUEST_H
