# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './resources/dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 300)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(30, 240, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.horizontalLayoutWidget = QtWidgets.QWidget(Dialog)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(20, 30, 361, 191))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.low = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.low.setObjectName("low")
        self.horizontalLayout.addWidget(self.low)
        self.medium = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.medium.setObjectName("medium")
        self.horizontalLayout.addWidget(self.medium)
        self.high = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.high.setObjectName("high")
        self.horizontalLayout.addWidget(self.high)

        self.retranslateUi(Dialog)
        # self.buttonBox.accepted.connect(Dialog.accept)
        # self.buttonBox.rejected.connect(Dialog.reject)
        self.high.linkActivated['QString'].connect(self.testUI)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.low.setText(_translate("Dialog", "TextLabel"))
        self.medium.setText(_translate("Dialog", "TextLabel"))
        self.high.setText(_translate("Dialog", "TextLabel"))

    def testUI(self):
        print("test")