# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'resources/menu.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_menuWindow(object):
    def setupUi(self, menuWindow):
        menuWindow.setObjectName("menuWindow")
        menuWindow.setEnabled(True)
        menuWindow.resize(1000, 785)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(menuWindow.sizePolicy().hasHeightForWidth())
        menuWindow.setSizePolicy(sizePolicy)
        menuWindow.setMaximumSize(QtCore.QSize(1000, 800))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 213, 213))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(247, 234, 234))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 107, 107))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(160, 142, 142))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 213, 213))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(247, 234, 234))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 213, 213))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(247, 234, 234))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 107, 107))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(160, 142, 142))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 213, 213))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(247, 234, 234))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 107, 107))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 213, 213))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(247, 234, 234))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 107, 107))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(160, 142, 142))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 107, 107))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 107, 107))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 213, 213))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 213, 213))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 213, 213))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.PlaceholderText, brush)
        menuWindow.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(14)
        menuWindow.setFont(font)
        menuWindow.setDocumentMode(False)
        menuWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.centralwidget = QtWidgets.QWidget(menuWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setEnabled(False)
        self.textEdit.setMaximumSize(QtCore.QSize(16777215, 50))
        self.textEdit.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.textEdit.setAcceptDrops(False)
        self.textEdit.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.textEdit.setReadOnly(True)
        self.textEdit.setAcceptRichText(False)
        self.textEdit.setObjectName("textEdit")
        self.verticalLayout.addWidget(self.textEdit)
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setMaximumSize(QtCore.QSize(1920, 1080))
        self.stackedWidget.setObjectName("stackedWidget")
        self.menuPage = QtWidgets.QWidget()
        self.menuPage.setObjectName("menuPage")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.menuPage)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 0, 0, 1, 1)
        self.name = QtWidgets.QLineEdit(self.menuPage)
        self.name.setObjectName("name")
        self.gridLayout.addWidget(self.name, 3, 2, 1, 1)
        self.selectExersiceButton = QtWidgets.QPushButton(self.menuPage)
        self.selectExersiceButton.setObjectName("selectExersiceButton")
        self.gridLayout.addWidget(self.selectExersiceButton, 8, 3, 1, 1)
        self.clearMenu = QtWidgets.QPushButton(self.menuPage)
        self.clearMenu.setObjectName("clearMenu")
        self.gridLayout.addWidget(self.clearMenu, 6, 0, 1, 1)
        self.surname = QtWidgets.QLineEdit(self.menuPage)
        self.surname.setObjectName("surname")
        self.gridLayout.addWidget(self.surname, 4, 2, 1, 1)
        self.nameLabel = QtWidgets.QLabel(self.menuPage)
        self.nameLabel.setObjectName("nameLabel")
        self.gridLayout.addWidget(self.nameLabel, 3, 0, 1, 1)
        self.mainImageHome = QtWidgets.QLabel(self.menuPage)
        self.mainImageHome.setMaximumSize(QtCore.QSize(480, 240))
        self.mainImageHome.setText("")
        self.mainImageHome.setScaledContents(True)
        self.mainImageHome.setAlignment(QtCore.Qt.AlignCenter)
        self.mainImageHome.setObjectName("mainImageHome")
        self.gridLayout.addWidget(self.mainImageHome, 0, 2, 1, 1, QtCore.Qt.AlignHCenter)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 6, 2, 1, 1)
        self.saveMenu = QtWidgets.QPushButton(self.menuPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.saveMenu.sizePolicy().hasHeightForWidth())
        self.saveMenu.setSizePolicy(sizePolicy)
        self.saveMenu.setSizeIncrement(QtCore.QSize(0, 0))
        self.saveMenu.setFlat(False)
        self.saveMenu.setObjectName("saveMenu")
        self.gridLayout.addWidget(self.saveMenu, 6, 3, 1, 1)
        self.selectExercise = QtWidgets.QComboBox(self.menuPage)
        self.selectExercise.setObjectName("selectExercise")
        self.gridLayout.addWidget(self.selectExercise, 8, 0, 1, 3)
        self.ageTextBox = QtWidgets.QLineEdit(self.menuPage)
        self.ageTextBox.setObjectName("ageTextBox")
        self.gridLayout.addWidget(self.ageTextBox, 5, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.menuPage)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 2, 2, 1, 1)
        self.surnameLabel = QtWidgets.QLabel(self.menuPage)
        self.surnameLabel.setObjectName("surnameLabel")
        self.gridLayout.addWidget(self.surnameLabel, 4, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.menuPage)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 7, 0, 1, 4)
        self.descriptionTxt = QtWidgets.QTextEdit(self.menuPage)
        self.descriptionTxt.setEnabled(False)
        self.descriptionTxt.setMaximumSize(QtCore.QSize(1500, 100))
        self.descriptionTxt.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.descriptionTxt.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.descriptionTxt.setObjectName("descriptionTxt")
        self.gridLayout.addWidget(self.descriptionTxt, 10, 0, 1, 3)
        self.ageLabel = QtWidgets.QLabel(self.menuPage)
        self.ageLabel.setObjectName("ageLabel")
        self.gridLayout.addWidget(self.ageLabel, 5, 0, 1, 1)
        self.pushButtonMainResults = QtWidgets.QPushButton(self.menuPage)
        self.pushButtonMainResults.setObjectName("pushButtonMainResults")
        self.gridLayout.addWidget(self.pushButtonMainResults, 9, 3, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.menuPage)
        self.feeback = QtWidgets.QWidget()
        self.feeback.setObjectName("feeback")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.feeback)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.gridLayout_10 = QtWidgets.QGridLayout()
        self.gridLayout_10.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout_10.setVerticalSpacing(30)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.normal = QtWidgets.QLabel(self.feeback)
        self.normal.setMaximumSize(QtCore.QSize(900, 600))
        self.normal.setScaledContents(True)
        self.normal.setObjectName("normal")
        self.gridLayout_10.addWidget(self.normal, 1, 1, 1, 1, QtCore.Qt.AlignHCenter)
        self.label_6 = QtWidgets.QLabel(self.feeback)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(24)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.gridLayout_10.addWidget(self.label_6, 0, 0, 1, 3, QtCore.Qt.AlignHCenter)
        self.easy = QtWidgets.QLabel(self.feeback)
        self.easy.setMaximumSize(QtCore.QSize(900, 600))
        self.easy.setScaledContents(True)
        self.easy.setObjectName("easy")
        self.gridLayout_10.addWidget(self.easy, 1, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.terminateButton = QtWidgets.QPushButton(self.feeback)
        self.terminateButton.setObjectName("terminateButton")
        self.gridLayout_10.addWidget(self.terminateButton, 3, 0, 1, 1)
        self.feedbackHardButton = QtWidgets.QPushButton(self.feeback)
        self.feedbackHardButton.setObjectName("feedbackHardButton")
        self.gridLayout_10.addWidget(self.feedbackHardButton, 2, 2, 1, 1)
        self.nextExersice = QtWidgets.QPushButton(self.feeback)
        self.nextExersice.setObjectName("nextExersice")
        self.gridLayout_10.addWidget(self.nextExersice, 3, 2, 1, 1)
        self.hard = QtWidgets.QLabel(self.feeback)
        self.hard.setMaximumSize(QtCore.QSize(900, 600))
        self.hard.setObjectName("hard")
        self.gridLayout_10.addWidget(self.hard, 1, 2, 1, 1, QtCore.Qt.AlignHCenter)
        self.feedbackEasyButton = QtWidgets.QPushButton(self.feeback)
        self.feedbackEasyButton.setObjectName("feedbackEasyButton")
        self.gridLayout_10.addWidget(self.feedbackEasyButton, 2, 0, 1, 1)
        self.feedbackNormalButton = QtWidgets.QPushButton(self.feeback)
        self.feedbackNormalButton.setObjectName("feedbackNormalButton")
        self.gridLayout_10.addWidget(self.feedbackNormalButton, 2, 1, 1, 1)
        self.gridLayout_11.addLayout(self.gridLayout_10, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.feeback)
        self.ex5Step2 = QtWidgets.QWidget()
        self.ex5Step2.setObjectName("ex5Step2")
        self.label_11 = QtWidgets.QLabel(self.ex5Step2)
        self.label_11.setGeometry(QtCore.QRect(10, 30, 881, 20))
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.go2Home = QtWidgets.QPushButton(self.ex5Step2)
        self.go2Home.setGeometry(QtCore.QRect(350, 250, 251, 121))
        self.go2Home.setObjectName("go2Home")
        self.stackedWidget.addWidget(self.ex5Step2)
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.page)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.lineResultsEx4 = QtWidgets.QLineEdit(self.page)
        self.lineResultsEx4.setObjectName("lineResultsEx4")
        self.gridLayout_3.addWidget(self.lineResultsEx4, 5, 2, 1, 1)
        self.pushButtoResultPrevius = QtWidgets.QPushButton(self.page)
        self.pushButtoResultPrevius.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButtoResultPrevius.setFlat(False)
        self.pushButtoResultPrevius.setObjectName("pushButtoResultPrevius")
        self.gridLayout_3.addWidget(self.pushButtoResultPrevius, 15, 2, 1, 1)
        self.labelResultEx11 = QtWidgets.QLabel(self.page)
        self.labelResultEx11.setObjectName("labelResultEx11")
        self.gridLayout_3.addWidget(self.labelResultEx11, 12, 0, 1, 1)
        self.labelResultEx9 = QtWidgets.QLabel(self.page)
        self.labelResultEx9.setObjectName("labelResultEx9")
        self.gridLayout_3.addWidget(self.labelResultEx9, 10, 0, 1, 1)
        self.labelResultName = QtWidgets.QLabel(self.page)
        self.labelResultName.setObjectName("labelResultName")
        self.gridLayout_3.addWidget(self.labelResultName, 0, 0, 1, 1)
        self.lineResultName = QtWidgets.QLineEdit(self.page)
        self.lineResultName.setObjectName("lineResultName")
        self.gridLayout_3.addWidget(self.lineResultName, 0, 2, 1, 1)
        self.labelResultEx1 = QtWidgets.QLabel(self.page)
        self.labelResultEx1.setObjectName("labelResultEx1")
        self.gridLayout_3.addWidget(self.labelResultEx1, 2, 0, 1, 1)
        self.lineResultsEx3 = QtWidgets.QLineEdit(self.page)
        self.lineResultsEx3.setObjectName("lineResultsEx3")
        self.gridLayout_3.addWidget(self.lineResultsEx3, 4, 2, 1, 1)
        self.labelResultSurname = QtWidgets.QLabel(self.page)
        self.labelResultSurname.setObjectName("labelResultSurname")
        self.gridLayout_3.addWidget(self.labelResultSurname, 1, 0, 1, 1)
        self.lineResultsEx11 = QtWidgets.QLineEdit(self.page)
        self.lineResultsEx11.setObjectName("lineResultsEx11")
        self.gridLayout_3.addWidget(self.lineResultsEx11, 12, 2, 1, 1)
        self.labelResultEx2 = QtWidgets.QLabel(self.page)
        self.labelResultEx2.setObjectName("labelResultEx2")
        self.gridLayout_3.addWidget(self.labelResultEx2, 3, 0, 1, 1)
        self.labelResultEx8 = QtWidgets.QLabel(self.page)
        self.labelResultEx8.setObjectName("labelResultEx8")
        self.gridLayout_3.addWidget(self.labelResultEx8, 9, 0, 1, 1)
        self.labelResultEx3 = QtWidgets.QLabel(self.page)
        self.labelResultEx3.setObjectName("labelResultEx3")
        self.gridLayout_3.addWidget(self.labelResultEx3, 4, 0, 1, 1)
        self.labelResultEx10 = QtWidgets.QLabel(self.page)
        self.labelResultEx10.setObjectName("labelResultEx10")
        self.gridLayout_3.addWidget(self.labelResultEx10, 11, 0, 1, 1)
        self.lineResultsEx8 = QtWidgets.QLineEdit(self.page)
        self.lineResultsEx8.setObjectName("lineResultsEx8")
        self.gridLayout_3.addWidget(self.lineResultsEx8, 9, 2, 1, 1)
        self.lineResultsEx5 = QtWidgets.QLineEdit(self.page)
        self.lineResultsEx5.setObjectName("lineResultsEx5")
        self.gridLayout_3.addWidget(self.lineResultsEx5, 6, 2, 1, 1)
        self.pushButtonResultsNext = QtWidgets.QPushButton(self.page)
        self.pushButtonResultsNext.setObjectName("pushButtonResultsNext")
        self.gridLayout_3.addWidget(self.pushButtonResultsNext, 14, 2, 1, 1)
        self.labelResultEx12 = QtWidgets.QLabel(self.page)
        self.labelResultEx12.setObjectName("labelResultEx12")
        self.gridLayout_3.addWidget(self.labelResultEx12, 13, 0, 1, 1)
        self.lineResultsSurname = QtWidgets.QLineEdit(self.page)
        self.lineResultsSurname.setObjectName("lineResultsSurname")
        self.gridLayout_3.addWidget(self.lineResultsSurname, 1, 2, 1, 1)
        self.lineResultsEx9 = QtWidgets.QLineEdit(self.page)
        self.lineResultsEx9.setObjectName("lineResultsEx9")
        self.gridLayout_3.addWidget(self.lineResultsEx9, 10, 2, 1, 1)
        self.labelResultEx5 = QtWidgets.QLabel(self.page)
        self.labelResultEx5.setObjectName("labelResultEx5")
        self.gridLayout_3.addWidget(self.labelResultEx5, 6, 0, 1, 1)
        self.labelResultEx4 = QtWidgets.QLabel(self.page)
        self.labelResultEx4.setObjectName("labelResultEx4")
        self.gridLayout_3.addWidget(self.labelResultEx4, 5, 0, 1, 1)
        self.labelResultEx7 = QtWidgets.QLabel(self.page)
        self.labelResultEx7.setObjectName("labelResultEx7")
        self.gridLayout_3.addWidget(self.labelResultEx7, 8, 0, 1, 1)
        self.lineResultsEx7 = QtWidgets.QLineEdit(self.page)
        self.lineResultsEx7.setObjectName("lineResultsEx7")
        self.gridLayout_3.addWidget(self.lineResultsEx7, 8, 2, 1, 1)
        self.lineResultsEx1 = QtWidgets.QLineEdit(self.page)
        self.lineResultsEx1.setObjectName("lineResultsEx1")
        self.gridLayout_3.addWidget(self.lineResultsEx1, 2, 2, 1, 1)
        self.lineResultsEx10 = QtWidgets.QLineEdit(self.page)
        self.lineResultsEx10.setObjectName("lineResultsEx10")
        self.gridLayout_3.addWidget(self.lineResultsEx10, 11, 2, 1, 1)
        self.lineResultsEx12 = QtWidgets.QLineEdit(self.page)
        self.lineResultsEx12.setObjectName("lineResultsEx12")
        self.gridLayout_3.addWidget(self.lineResultsEx12, 13, 2, 1, 1)
        self.lineResultsEx2 = QtWidgets.QLineEdit(self.page)
        self.lineResultsEx2.setObjectName("lineResultsEx2")
        self.gridLayout_3.addWidget(self.lineResultsEx2, 3, 2, 1, 1)
        self.lineResultsEx6 = QtWidgets.QLineEdit(self.page)
        self.lineResultsEx6.setObjectName("lineResultsEx6")
        self.gridLayout_3.addWidget(self.lineResultsEx6, 7, 2, 1, 1)
        self.labelResultEx6 = QtWidgets.QLabel(self.page)
        self.labelResultEx6.setObjectName("labelResultEx6")
        self.gridLayout_3.addWidget(self.labelResultEx6, 7, 0, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout_3, 1, 0, 1, 1)
        self.comboBox = QtWidgets.QComboBox(self.page)
        self.comboBox.setObjectName("comboBox")
        self.gridLayout_5.addWidget(self.comboBox, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.page)
        self.verticalLayout.addWidget(self.stackedWidget)
        self.gridLayout_2.addLayout(self.verticalLayout, 0, 0, 1, 1)
        menuWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(menuWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1000, 28))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        self.menuEdit = QtWidgets.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        self.menuSetting = QtWidgets.QMenu(self.menubar)
        self.menuSetting.setObjectName("menuSetting")
        self.menuWindows = QtWidgets.QMenu(self.menubar)
        self.menuWindows.setObjectName("menuWindows")
        self.menuMove_to_Activity = QtWidgets.QMenu(self.menuWindows)
        self.menuMove_to_Activity.setObjectName("menuMove_to_Activity")
        self.menuAbout = QtWidgets.QMenu(self.menubar)
        self.menuAbout.setObjectName("menuAbout")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        menuWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(menuWindow)
        self.statusbar.setObjectName("statusbar")
        menuWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(menuWindow)
        self.toolBar.setObjectName("toolBar")
        menuWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionAAbout = QtWidgets.QAction(menuWindow)
        self.actionAAbout.setObjectName("actionAAbout")
        self.actionActivity_1 = QtWidgets.QAction(menuWindow)
        self.actionActivity_1.setObjectName("actionActivity_1")
        self.actionActivity_2 = QtWidgets.QAction(menuWindow)
        self.actionActivity_2.setObjectName("actionActivity_2")
        self.actionActivity_3 = QtWidgets.QAction(menuWindow)
        self.actionActivity_3.setObjectName("actionActivity_3")
        self.actionActivity_4 = QtWidgets.QAction(menuWindow)
        self.actionActivity_4.setObjectName("actionActivity_4")
        self.actionActivity_5 = QtWidgets.QAction(menuWindow)
        self.actionActivity_5.setObjectName("actionActivity_5")
        self.actionActivity_6 = QtWidgets.QAction(menuWindow)
        self.actionActivity_6.setObjectName("actionActivity_6")
        self.actionMain_Menu = QtWidgets.QAction(menuWindow)
        self.actionMain_Menu.setObjectName("actionMain_Menu")
        self.actionExport_Data = QtWidgets.QAction(menuWindow)
        self.actionExport_Data.setObjectName("actionExport_Data")
        self.actionMedia_Files_Folder = QtWidgets.QAction(menuWindow)
        self.actionMedia_Files_Folder.setObjectName("actionMedia_Files_Folder")
        self.action6 = QtWidgets.QAction(menuWindow)
        self.action6.setObjectName("action6")
        self.action7 = QtWidgets.QAction(menuWindow)
        self.action7.setObjectName("action7")
        self.action8 = QtWidgets.QAction(menuWindow)
        self.action8.setObjectName("action8")
        self.action9 = QtWidgets.QAction(menuWindow)
        self.action9.setObjectName("action9")
        self.action10 = QtWidgets.QAction(menuWindow)
        self.action10.setObjectName("action10")
        self.action11 = QtWidgets.QAction(menuWindow)
        self.action11.setObjectName("action11")
        self.menu.addAction(self.actionExport_Data)
        self.menuSetting.addAction(self.actionMedia_Files_Folder)
        self.menuMove_to_Activity.addAction(self.actionActivity_1)
        self.menuMove_to_Activity.addAction(self.actionActivity_2)
        self.menuMove_to_Activity.addAction(self.actionActivity_3)
        self.menuMove_to_Activity.addAction(self.actionActivity_4)
        self.menuMove_to_Activity.addAction(self.actionActivity_5)
        self.menuMove_to_Activity.addAction(self.actionActivity_6)
        self.menuMove_to_Activity.addAction(self.action6)
        self.menuMove_to_Activity.addAction(self.action7)
        self.menuMove_to_Activity.addAction(self.action8)
        self.menuMove_to_Activity.addAction(self.action9)
        self.menuMove_to_Activity.addAction(self.action10)
        self.menuMove_to_Activity.addAction(self.action11)
        self.menuWindows.addAction(self.menuMove_to_Activity.menuAction())
        self.menuWindows.addAction(self.actionMain_Menu)
        self.menuHelp.addAction(self.actionAAbout)
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuSetting.menuAction())
        self.menubar.addAction(self.menuWindows.menuAction())
        self.menubar.addAction(self.menuAbout.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(menuWindow)
        self.stackedWidget.setCurrentIndex(3)
        QtCore.QMetaObject.connectSlotsByName(menuWindow)

    def retranslateUi(self, menuWindow):
        _translate = QtCore.QCoreApplication.translate
        menuWindow.setWindowTitle(_translate("menuWindow", "Αρχική οθόνη "))
        self.textEdit.setHtml(_translate("menuWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans\'; font-size:14pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'arial,sans-serif\'; font-size:24pt; color:#8ab4f8;\">Εκπαιδευτική εφαρμογή</span></p></body></html>"))
        self.selectExersiceButton.setText(_translate("menuWindow", "Έναρξη"))
        self.clearMenu.setText(_translate("menuWindow", "Εκκαθάριση"))
        self.nameLabel.setText(_translate("menuWindow", "Όνομα"))
        self.saveMenu.setText(_translate("menuWindow", "Αποθήκευση"))
        self.label_2.setText(_translate("menuWindow", "Προσωπικά στοιχεία"))
        self.surnameLabel.setText(_translate("menuWindow", "Επίθετο"))
        self.label.setText(_translate("menuWindow", "Διαθέσιμες επιλογές"))
        self.ageLabel.setText(_translate("menuWindow", "Ηλικία"))
        self.pushButtonMainResults.setText(_translate("menuWindow", "Αποτελέσματα"))
        self.normal.setText(_translate("menuWindow", "Normal"))
        self.label_6.setText(_translate("menuWindow", "Πόσο εύκολος σου φάνηκε ο γρίφος"))
        self.easy.setText(_translate("menuWindow", "Easy"))
        self.terminateButton.setText(_translate("menuWindow", "\n"
"Τερματισμός\n"
""))
        self.feedbackHardButton.setText(_translate("menuWindow", "\n"
"Δύσκολος\n"
""))
        self.nextExersice.setText(_translate("menuWindow", "\n"
"Επόμενη δραστηριότητα\n"
""))
        self.hard.setText(_translate("menuWindow", "Hard"))
        self.feedbackEasyButton.setText(_translate("menuWindow", "\n"
"Εύκολος\n"
""))
        self.feedbackNormalButton.setText(_translate("menuWindow", "\n"
"Έτσι και έτσι\n"
""))
        self.label_11.setText(_translate("menuWindow", "Τέλος"))
        self.go2Home.setText(_translate("menuWindow", "Αρχικό Μενού"))
        self.pushButtoResultPrevius.setText(_translate("menuWindow", "Προηγούμενο"))
        self.labelResultEx11.setText(_translate("menuWindow", "Ένα παιγνίδι με γρίφους 2"))
        self.labelResultEx9.setText(_translate("menuWindow", "Ο κοκκινός στρατός"))
        self.labelResultName.setText(_translate("menuWindow", "Όνομα"))
        self.labelResultEx1.setText(_translate("menuWindow", "Το λιοντάρι και τα παπάκια"))
        self.labelResultSurname.setText(_translate("menuWindow", "Επίθετο"))
        self.labelResultEx2.setText(_translate("menuWindow", "Ασκηση προσοχής"))
        self.labelResultEx8.setText(_translate("menuWindow", "Ο Μάξιμος"))
        self.labelResultEx3.setText(_translate("menuWindow", "Ο Γιωργάκης και η σοκολάτα"))
        self.labelResultEx10.setText(_translate("menuWindow", "Η Σοφία στο σχολείο"))
        self.pushButtonResultsNext.setText(_translate("menuWindow", "Επόμενο"))
        self.labelResultEx12.setText(_translate("menuWindow", "Τι δείχνουν οι εικόνες 2"))
        self.labelResultEx5.setText(_translate("menuWindow", "Ένα παιγνίδι με γρίφους"))
        self.labelResultEx4.setText(_translate("menuWindow", "Η Μαρία και η μαμά της"))
        self.labelResultEx7.setText(_translate("menuWindow", "Η μαμά καγκούρο"))
        self.labelResultEx6.setText(_translate("menuWindow", "Τι δείχνουν οι εικόνες"))
        self.menu.setTitle(_translate("menuWindow", "Αρχείο"))
        self.menuEdit.setTitle(_translate("menuWindow", "Edit"))
        self.menuSetting.setTitle(_translate("menuWindow", "Setting"))
        self.menuWindows.setTitle(_translate("menuWindow", "Windows"))
        self.menuMove_to_Activity.setTitle(_translate("menuWindow", "Move to Activity"))
        self.menuAbout.setTitle(_translate("menuWindow", "About"))
        self.menuHelp.setTitle(_translate("menuWindow", "Help"))
        self.toolBar.setWindowTitle(_translate("menuWindow", "toolBar"))
        self.actionAAbout.setText(_translate("menuWindow", "About"))
        self.actionActivity_1.setText(_translate("menuWindow", "1"))
        self.actionActivity_2.setText(_translate("menuWindow", "2"))
        self.actionActivity_3.setText(_translate("menuWindow", "3"))
        self.actionActivity_4.setText(_translate("menuWindow", "4"))
        self.actionActivity_5.setText(_translate("menuWindow", "5"))
        self.actionActivity_6.setText(_translate("menuWindow", "6"))
        self.actionMain_Menu.setText(_translate("menuWindow", "Main Menu"))
        self.actionExport_Data.setText(_translate("menuWindow", "Export Data"))
        self.actionMedia_Files_Folder.setText(_translate("menuWindow", "Media Files Folder"))
        self.action6.setText(_translate("menuWindow", "6"))
        self.action7.setText(_translate("menuWindow", "7"))
        self.action8.setText(_translate("menuWindow", "8"))
        self.action9.setText(_translate("menuWindow", "9"))
        self.action10.setText(_translate("menuWindow", "10"))
        self.action11.setText(_translate("menuWindow", "11"))
