# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'resources/menu.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_menuWindow(object):
    def setupUi(self, menuWindow):
        menuWindow.setObjectName("menuWindow")
        menuWindow.setEnabled(True)
        menuWindow.resize(1000, 792)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(menuWindow.sizePolicy().hasHeightForWidth())
        menuWindow.setSizePolicy(sizePolicy)
        menuWindow.setMaximumSize(QtCore.QSize(1000, 800))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 213, 213))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(247, 234, 234))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 107, 107))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(160, 142, 142))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 213, 213))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(247, 234, 234))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 213, 213))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(247, 234, 234))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 107, 107))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(160, 142, 142))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 213, 213))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(247, 234, 234))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 107, 107))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 213, 213))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(247, 234, 234))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 107, 107))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(160, 142, 142))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 107, 107))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 107, 107))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 213, 213))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 213, 213))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 213, 213))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.PlaceholderText, brush)
        menuWindow.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(14)
        menuWindow.setFont(font)
        menuWindow.setDocumentMode(False)
        menuWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.centralwidget = QtWidgets.QWidget(menuWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setEnabled(False)
        self.textEdit.setMaximumSize(QtCore.QSize(16777215, 50))
        self.textEdit.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.textEdit.setAcceptDrops(False)
        self.textEdit.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.textEdit.setReadOnly(True)
        self.textEdit.setAcceptRichText(False)
        self.textEdit.setObjectName("textEdit")
        self.verticalLayout.addWidget(self.textEdit)
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setMaximumSize(QtCore.QSize(1920, 1080))
        self.stackedWidget.setObjectName("stackedWidget")
        self.menuPage = QtWidgets.QWidget()
        self.menuPage.setObjectName("menuPage")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.menuPage)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 0, 0, 1, 1)
        self.name = QtWidgets.QLineEdit(self.menuPage)
        self.name.setObjectName("name")
        self.gridLayout.addWidget(self.name, 3, 2, 1, 1)
        self.selectExersiceButton = QtWidgets.QPushButton(self.menuPage)
        self.selectExersiceButton.setObjectName("selectExersiceButton")
        self.gridLayout.addWidget(self.selectExersiceButton, 8, 3, 1, 1)
        self.clearMenu = QtWidgets.QPushButton(self.menuPage)
        self.clearMenu.setObjectName("clearMenu")
        self.gridLayout.addWidget(self.clearMenu, 6, 0, 1, 1)
        self.surname = QtWidgets.QLineEdit(self.menuPage)
        self.surname.setObjectName("surname")
        self.gridLayout.addWidget(self.surname, 4, 2, 1, 1)
        self.nameLabel = QtWidgets.QLabel(self.menuPage)
        self.nameLabel.setObjectName("nameLabel")
        self.gridLayout.addWidget(self.nameLabel, 3, 0, 1, 1)
        self.mainImageHome = QtWidgets.QLabel(self.menuPage)
        self.mainImageHome.setMaximumSize(QtCore.QSize(480, 240))
        self.mainImageHome.setText("")
        self.mainImageHome.setScaledContents(True)
        self.mainImageHome.setAlignment(QtCore.Qt.AlignCenter)
        self.mainImageHome.setObjectName("mainImageHome")
        self.gridLayout.addWidget(self.mainImageHome, 0, 2, 1, 1, QtCore.Qt.AlignHCenter)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 6, 2, 1, 1)
        self.saveMenu = QtWidgets.QPushButton(self.menuPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.saveMenu.sizePolicy().hasHeightForWidth())
        self.saveMenu.setSizePolicy(sizePolicy)
        self.saveMenu.setSizeIncrement(QtCore.QSize(0, 0))
        self.saveMenu.setFlat(False)
        self.saveMenu.setObjectName("saveMenu")
        self.gridLayout.addWidget(self.saveMenu, 6, 3, 1, 1)
        self.selectExercise = QtWidgets.QComboBox(self.menuPage)
        self.selectExercise.setObjectName("selectExercise")
        self.gridLayout.addWidget(self.selectExercise, 8, 0, 1, 3)
        self.ageTextBox = QtWidgets.QLineEdit(self.menuPage)
        self.ageTextBox.setObjectName("ageTextBox")
        self.gridLayout.addWidget(self.ageTextBox, 5, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.menuPage)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 2, 2, 1, 1)
        self.surnameLabel = QtWidgets.QLabel(self.menuPage)
        self.surnameLabel.setObjectName("surnameLabel")
        self.gridLayout.addWidget(self.surnameLabel, 4, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.menuPage)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 7, 0, 1, 4)
        self.descriptionTxt = QtWidgets.QTextEdit(self.menuPage)
        self.descriptionTxt.setEnabled(False)
        self.descriptionTxt.setMaximumSize(QtCore.QSize(1500, 100))
        self.descriptionTxt.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.descriptionTxt.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.descriptionTxt.setObjectName("descriptionTxt")
        self.gridLayout.addWidget(self.descriptionTxt, 10, 0, 1, 3)
        self.ageLabel = QtWidgets.QLabel(self.menuPage)
        self.ageLabel.setObjectName("ageLabel")
        self.gridLayout.addWidget(self.ageLabel, 5, 0, 1, 1)
        self.pushButtonMainResults = QtWidgets.QPushButton(self.menuPage)
        self.pushButtonMainResults.setObjectName("pushButtonMainResults")
        self.gridLayout.addWidget(self.pushButtonMainResults, 9, 3, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.menuPage)
        self.feeback = QtWidgets.QWidget()
        self.feeback.setObjectName("feeback")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.feeback)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.gridLayout_10 = QtWidgets.QGridLayout()
        self.gridLayout_10.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout_10.setVerticalSpacing(30)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.normal = QtWidgets.QLabel(self.feeback)
        self.normal.setMaximumSize(QtCore.QSize(900, 600))
        self.normal.setScaledContents(True)
        self.normal.setObjectName("normal")
        self.gridLayout_10.addWidget(self.normal, 1, 1, 1, 1, QtCore.Qt.AlignHCenter)
        self.label_6 = QtWidgets.QLabel(self.feeback)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(24)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.gridLayout_10.addWidget(self.label_6, 0, 0, 1, 3, QtCore.Qt.AlignHCenter)
        self.easy = QtWidgets.QLabel(self.feeback)
        self.easy.setMaximumSize(QtCore.QSize(900, 600))
        self.easy.setScaledContents(True)
        self.easy.setObjectName("easy")
        self.gridLayout_10.addWidget(self.easy, 1, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.terminateButton = QtWidgets.QPushButton(self.feeback)
        self.terminateButton.setObjectName("terminateButton")
        self.gridLayout_10.addWidget(self.terminateButton, 3, 0, 1, 1)
        self.feedbackHardButton = QtWidgets.QPushButton(self.feeback)
        self.feedbackHardButton.setObjectName("feedbackHardButton")
        self.gridLayout_10.addWidget(self.feedbackHardButton, 2, 2, 1, 1)
        self.nextExersice = QtWidgets.QPushButton(self.feeback)
        self.nextExersice.setObjectName("nextExersice")
        self.gridLayout_10.addWidget(self.nextExersice, 3, 2, 1, 1)
        self.hard = QtWidgets.QLabel(self.feeback)
        self.hard.setMaximumSize(QtCore.QSize(900, 600))
        self.hard.setObjectName("hard")
        self.gridLayout_10.addWidget(self.hard, 1, 2, 1, 1, QtCore.Qt.AlignHCenter)
        self.feedbackEasyButton = QtWidgets.QPushButton(self.feeback)
        self.feedbackEasyButton.setObjectName("feedbackEasyButton")
        self.gridLayout_10.addWidget(self.feedbackEasyButton, 2, 0, 1, 1)
        self.feedbackNormalButton = QtWidgets.QPushButton(self.feeback)
        self.feedbackNormalButton.setObjectName("feedbackNormalButton")
        self.gridLayout_10.addWidget(self.feedbackNormalButton, 2, 1, 1, 1)
        self.gridLayout_11.addLayout(self.gridLayout_10, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.feeback)
        self.ex5Step2 = QtWidgets.QWidget()
        self.ex5Step2.setObjectName("ex5Step2")
        self.label_11 = QtWidgets.QLabel(self.ex5Step2)
        self.label_11.setGeometry(QtCore.QRect(10, 30, 881, 20))
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.go2Home = QtWidgets.QPushButton(self.ex5Step2)
        self.go2Home.setGeometry(QtCore.QRect(350, 250, 251, 121))
        self.go2Home.setObjectName("go2Home")
        self.stackedWidget.addWidget(self.ex5Step2)
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.page)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.checkBox_30 = QtWidgets.QCheckBox(self.page)
        self.checkBox_30.setText("")
        self.checkBox_30.setObjectName("checkBox_30")
        self.gridLayout_3.addWidget(self.checkBox_30, 12, 5, 1, 1)
        self.checkBox_8 = QtWidgets.QCheckBox(self.page)
        self.checkBox_8.setText("")
        self.checkBox_8.setObjectName("checkBox_8")
        self.gridLayout_3.addWidget(self.checkBox_8, 14, 3, 1, 1)
        self.labelResultEx8 = QtWidgets.QLabel(self.page)
        self.labelResultEx8.setObjectName("labelResultEx8")
        self.gridLayout_3.addWidget(self.labelResultEx8, 14, 0, 1, 1)
        self.checkBox_23 = QtWidgets.QCheckBox(self.page)
        self.checkBox_23.setText("")
        self.checkBox_23.setObjectName("checkBox_23")
        self.gridLayout_3.addWidget(self.checkBox_23, 17, 4, 1, 1)
        self.checkBox_28 = QtWidgets.QCheckBox(self.page)
        self.checkBox_28.setText("")
        self.checkBox_28.setObjectName("checkBox_28")
        self.gridLayout_3.addWidget(self.checkBox_28, 10, 5, 1, 1)
        self.checkBox_32 = QtWidgets.QCheckBox(self.page)
        self.checkBox_32.setText("")
        self.checkBox_32.setObjectName("checkBox_32")
        self.gridLayout_3.addWidget(self.checkBox_32, 14, 5, 1, 1)
        self.dateEdit = QtWidgets.QDateEdit(self.page)
        self.dateEdit.setObjectName("dateEdit")
        self.gridLayout_3.addWidget(self.dateEdit, 1, 5, 1, 1)
        self.labelResultEx6 = QtWidgets.QLabel(self.page)
        self.labelResultEx6.setObjectName("labelResultEx6")
        self.gridLayout_3.addWidget(self.labelResultEx6, 12, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.page)
        self.label_4.setObjectName("label_4")
        self.gridLayout_3.addWidget(self.label_4, 4, 5, 1, 1)
        self.checkBox_5 = QtWidgets.QCheckBox(self.page)
        self.checkBox_5.setText("")
        self.checkBox_5.setObjectName("checkBox_5")
        self.gridLayout_3.addWidget(self.checkBox_5, 11, 3, 1, 1)
        self.labelResultEx1 = QtWidgets.QLabel(self.page)
        self.labelResultEx1.setObjectName("labelResultEx1")
        self.gridLayout_3.addWidget(self.labelResultEx1, 7, 0, 1, 1)
        self.checkBox_33 = QtWidgets.QCheckBox(self.page)
        self.checkBox_33.setText("")
        self.checkBox_33.setObjectName("checkBox_33")
        self.gridLayout_3.addWidget(self.checkBox_33, 15, 5, 1, 1)
        self.labelResultName = QtWidgets.QLabel(self.page)
        self.labelResultName.setObjectName("labelResultName")
        self.gridLayout_3.addWidget(self.labelResultName, 3, 0, 1, 1)
        self.labelResultSurname = QtWidgets.QLabel(self.page)
        self.labelResultSurname.setObjectName("labelResultSurname")
        self.gridLayout_3.addWidget(self.labelResultSurname, 4, 0, 1, 1)
        self.checkBox_18 = QtWidgets.QCheckBox(self.page)
        self.checkBox_18.setText("")
        self.checkBox_18.setObjectName("checkBox_18")
        self.gridLayout_3.addWidget(self.checkBox_18, 12, 4, 1, 1)
        self.labelResultEx12 = QtWidgets.QLabel(self.page)
        self.labelResultEx12.setObjectName("labelResultEx12")
        self.gridLayout_3.addWidget(self.labelResultEx12, 18, 0, 1, 1)
        self.lineResultsEx8 = QtWidgets.QLineEdit(self.page)
        self.lineResultsEx8.setObjectName("lineResultsEx8")
        self.gridLayout_3.addWidget(self.lineResultsEx8, 14, 2, 1, 1)
        self.checkBox_11 = QtWidgets.QCheckBox(self.page)
        self.checkBox_11.setText("")
        self.checkBox_11.setObjectName("checkBox_11")
        self.gridLayout_3.addWidget(self.checkBox_11, 17, 3, 1, 1)
        self.checkBox_15 = QtWidgets.QCheckBox(self.page)
        self.checkBox_15.setText("")
        self.checkBox_15.setObjectName("checkBox_15")
        self.gridLayout_3.addWidget(self.checkBox_15, 9, 4, 1, 1)
        self.lineResultsEx10 = QtWidgets.QLineEdit(self.page)
        self.lineResultsEx10.setObjectName("lineResultsEx10")
        self.gridLayout_3.addWidget(self.lineResultsEx10, 16, 2, 1, 1)
        self.lineResultsEx9 = QtWidgets.QLineEdit(self.page)
        self.lineResultsEx9.setObjectName("lineResultsEx9")
        self.gridLayout_3.addWidget(self.lineResultsEx9, 15, 2, 1, 1)
        self.checkBox_4 = QtWidgets.QCheckBox(self.page)
        self.checkBox_4.setText("")
        self.checkBox_4.setObjectName("checkBox_4")
        self.gridLayout_3.addWidget(self.checkBox_4, 10, 3, 1, 1)
        self.checkBox_17 = QtWidgets.QCheckBox(self.page)
        self.checkBox_17.setText("")
        self.checkBox_17.setObjectName("checkBox_17")
        self.gridLayout_3.addWidget(self.checkBox_17, 11, 4, 1, 1)
        self.checkBox_24 = QtWidgets.QCheckBox(self.page)
        self.checkBox_24.setText("")
        self.checkBox_24.setObjectName("checkBox_24")
        self.gridLayout_3.addWidget(self.checkBox_24, 18, 4, 1, 1)
        self.lineResultsEx4 = QtWidgets.QLineEdit(self.page)
        self.lineResultsEx4.setObjectName("lineResultsEx4")
        self.gridLayout_3.addWidget(self.lineResultsEx4, 10, 2, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.page)
        self.label_8.setObjectName("label_8")
        self.gridLayout_3.addWidget(self.label_8, 1, 4, 1, 1)
        self.checkBox_31 = QtWidgets.QCheckBox(self.page)
        self.checkBox_31.setText("")
        self.checkBox_31.setObjectName("checkBox_31")
        self.gridLayout_3.addWidget(self.checkBox_31, 13, 5, 1, 1)
        self.checkBox_25 = QtWidgets.QCheckBox(self.page)
        self.checkBox_25.setText("")
        self.checkBox_25.setObjectName("checkBox_25")
        self.gridLayout_3.addWidget(self.checkBox_25, 7, 5, 1, 1)
        self.lineResultsEx3 = QtWidgets.QLineEdit(self.page)
        self.lineResultsEx3.setObjectName("lineResultsEx3")
        self.gridLayout_3.addWidget(self.lineResultsEx3, 9, 2, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem2, 5, 2, 1, 1)
        self.checkBox_6 = QtWidgets.QCheckBox(self.page)
        self.checkBox_6.setText("")
        self.checkBox_6.setObjectName("checkBox_6")
        self.gridLayout_3.addWidget(self.checkBox_6, 12, 3, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.page)
        self.label_7.setObjectName("label_7")
        self.gridLayout_3.addWidget(self.label_7, 1, 0, 1, 1)
        self.checkBox_21 = QtWidgets.QCheckBox(self.page)
        self.checkBox_21.setText("")
        self.checkBox_21.setObjectName("checkBox_21")
        self.gridLayout_3.addWidget(self.checkBox_21, 15, 4, 1, 1)
        self.comboBox = QtWidgets.QComboBox(self.page)
        self.comboBox.setObjectName("comboBox")
        self.gridLayout_3.addWidget(self.comboBox, 1, 2, 1, 2)
        self.label_5 = QtWidgets.QLabel(self.page)
        self.label_5.setObjectName("label_5")
        self.gridLayout_3.addWidget(self.label_5, 4, 4, 1, 1)
        self.checkBox_26 = QtWidgets.QCheckBox(self.page)
        self.checkBox_26.setText("")
        self.checkBox_26.setObjectName("checkBox_26")
        self.gridLayout_3.addWidget(self.checkBox_26, 8, 5, 1, 1)
        self.lineResultsEx2 = QtWidgets.QLineEdit(self.page)
        self.lineResultsEx2.setObjectName("lineResultsEx2")
        self.gridLayout_3.addWidget(self.lineResultsEx2, 8, 2, 1, 1)
        self.labelResultEx7 = QtWidgets.QLabel(self.page)
        self.labelResultEx7.setObjectName("labelResultEx7")
        self.gridLayout_3.addWidget(self.labelResultEx7, 13, 0, 1, 1)
        self.labelResultEx4 = QtWidgets.QLabel(self.page)
        self.labelResultEx4.setObjectName("labelResultEx4")
        self.gridLayout_3.addWidget(self.labelResultEx4, 10, 0, 1, 1)
        self.checkBox_16 = QtWidgets.QCheckBox(self.page)
        self.checkBox_16.setText("")
        self.checkBox_16.setObjectName("checkBox_16")
        self.gridLayout_3.addWidget(self.checkBox_16, 10, 4, 1, 1)
        self.checkBox_29 = QtWidgets.QCheckBox(self.page)
        self.checkBox_29.setText("")
        self.checkBox_29.setObjectName("checkBox_29")
        self.gridLayout_3.addWidget(self.checkBox_29, 11, 5, 1, 1)
        self.checkBox_14 = QtWidgets.QCheckBox(self.page)
        self.checkBox_14.setText("")
        self.checkBox_14.setObjectName("checkBox_14")
        self.gridLayout_3.addWidget(self.checkBox_14, 8, 4, 1, 1)
        self.lineResultsSurname = QtWidgets.QLineEdit(self.page)
        self.lineResultsSurname.setObjectName("lineResultsSurname")
        self.gridLayout_3.addWidget(self.lineResultsSurname, 4, 2, 1, 1)
        self.lineResultsEx11 = QtWidgets.QLineEdit(self.page)
        self.lineResultsEx11.setObjectName("lineResultsEx11")
        self.gridLayout_3.addWidget(self.lineResultsEx11, 17, 2, 1, 1)
        self.checkBox_9 = QtWidgets.QCheckBox(self.page)
        self.checkBox_9.setText("")
        self.checkBox_9.setObjectName("checkBox_9")
        self.gridLayout_3.addWidget(self.checkBox_9, 15, 3, 1, 1)
        self.checkBox_22 = QtWidgets.QCheckBox(self.page)
        self.checkBox_22.setText("")
        self.checkBox_22.setObjectName("checkBox_22")
        self.gridLayout_3.addWidget(self.checkBox_22, 16, 4, 1, 1)
        self.lineResultsEx6 = QtWidgets.QLineEdit(self.page)
        self.lineResultsEx6.setObjectName("lineResultsEx6")
        self.gridLayout_3.addWidget(self.lineResultsEx6, 12, 2, 1, 1)
        self.checkBox_35 = QtWidgets.QCheckBox(self.page)
        self.checkBox_35.setText("")
        self.checkBox_35.setObjectName("checkBox_35")
        self.gridLayout_3.addWidget(self.checkBox_35, 17, 5, 1, 1)
        self.checkBox_2 = QtWidgets.QCheckBox(self.page)
        self.checkBox_2.setText("")
        self.checkBox_2.setObjectName("checkBox_2")
        self.gridLayout_3.addWidget(self.checkBox_2, 8, 3, 1, 1)
        self.checkBox_20 = QtWidgets.QCheckBox(self.page)
        self.checkBox_20.setText("")
        self.checkBox_20.setObjectName("checkBox_20")
        self.gridLayout_3.addWidget(self.checkBox_20, 14, 4, 1, 1)
        self.checkBox = QtWidgets.QCheckBox(self.page)
        self.checkBox.setText("")
        self.checkBox.setObjectName("checkBox")
        self.gridLayout_3.addWidget(self.checkBox, 7, 3, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.page)
        self.label_3.setObjectName("label_3")
        self.gridLayout_3.addWidget(self.label_3, 4, 3, 1, 1)
        self.lineResultName = QtWidgets.QLineEdit(self.page)
        self.lineResultName.setObjectName("lineResultName")
        self.gridLayout_3.addWidget(self.lineResultName, 3, 2, 1, 1)
        self.checkBox_7 = QtWidgets.QCheckBox(self.page)
        self.checkBox_7.setText("")
        self.checkBox_7.setObjectName("checkBox_7")
        self.gridLayout_3.addWidget(self.checkBox_7, 13, 3, 1, 1)
        self.checkBox_27 = QtWidgets.QCheckBox(self.page)
        self.checkBox_27.setText("")
        self.checkBox_27.setObjectName("checkBox_27")
        self.gridLayout_3.addWidget(self.checkBox_27, 9, 5, 1, 1)
        self.lineResultsEx12 = QtWidgets.QLineEdit(self.page)
        self.lineResultsEx12.setObjectName("lineResultsEx12")
        self.gridLayout_3.addWidget(self.lineResultsEx12, 18, 2, 1, 1)
        self.lineResultsEx7 = QtWidgets.QLineEdit(self.page)
        self.lineResultsEx7.setObjectName("lineResultsEx7")
        self.gridLayout_3.addWidget(self.lineResultsEx7, 13, 2, 1, 1)
        self.labelResultEx2 = QtWidgets.QLabel(self.page)
        self.labelResultEx2.setObjectName("labelResultEx2")
        self.gridLayout_3.addWidget(self.labelResultEx2, 8, 0, 1, 1)
        self.checkBox_19 = QtWidgets.QCheckBox(self.page)
        self.checkBox_19.setText("")
        self.checkBox_19.setObjectName("checkBox_19")
        self.gridLayout_3.addWidget(self.checkBox_19, 13, 4, 1, 1)
        self.lineResultsEx5 = QtWidgets.QLineEdit(self.page)
        self.lineResultsEx5.setObjectName("lineResultsEx5")
        self.gridLayout_3.addWidget(self.lineResultsEx5, 11, 2, 1, 1)
        self.pushButtonResultsNext = QtWidgets.QPushButton(self.page)
        self.pushButtonResultsNext.setObjectName("pushButtonResultsNext")
        self.gridLayout_3.addWidget(self.pushButtonResultsNext, 20, 5, 1, 1)
        self.pushButtoResultPrevius = QtWidgets.QPushButton(self.page)
        self.pushButtoResultPrevius.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButtoResultPrevius.setFlat(False)
        self.pushButtoResultPrevius.setObjectName("pushButtoResultPrevius")
        self.gridLayout_3.addWidget(self.pushButtoResultPrevius, 20, 3, 1, 1)
        self.checkBox_12 = QtWidgets.QCheckBox(self.page)
        self.checkBox_12.setText("")
        self.checkBox_12.setObjectName("checkBox_12")
        self.gridLayout_3.addWidget(self.checkBox_12, 18, 3, 1, 1)
        self.checkBox_3 = QtWidgets.QCheckBox(self.page)
        self.checkBox_3.setText("")
        self.checkBox_3.setObjectName("checkBox_3")
        self.gridLayout_3.addWidget(self.checkBox_3, 9, 3, 1, 1)
        self.checkBox_34 = QtWidgets.QCheckBox(self.page)
        self.checkBox_34.setText("")
        self.checkBox_34.setObjectName("checkBox_34")
        self.gridLayout_3.addWidget(self.checkBox_34, 16, 5, 1, 1)
        self.labelResultEx10 = QtWidgets.QLabel(self.page)
        self.labelResultEx10.setObjectName("labelResultEx10")
        self.gridLayout_3.addWidget(self.labelResultEx10, 16, 0, 1, 1)
        self.checkBox_13 = QtWidgets.QCheckBox(self.page)
        self.checkBox_13.setText("")
        self.checkBox_13.setObjectName("checkBox_13")
        self.gridLayout_3.addWidget(self.checkBox_13, 7, 4, 1, 1)
        self.lineResultsEx1 = QtWidgets.QLineEdit(self.page)
        self.lineResultsEx1.setObjectName("lineResultsEx1")
        self.gridLayout_3.addWidget(self.lineResultsEx1, 7, 2, 1, 1)
        self.labelResultEx3 = QtWidgets.QLabel(self.page)
        self.labelResultEx3.setObjectName("labelResultEx3")
        self.gridLayout_3.addWidget(self.labelResultEx3, 9, 0, 1, 1)
        self.labelResultEx9 = QtWidgets.QLabel(self.page)
        self.labelResultEx9.setObjectName("labelResultEx9")
        self.gridLayout_3.addWidget(self.labelResultEx9, 15, 0, 1, 1)
        self.checkBox_36 = QtWidgets.QCheckBox(self.page)
        self.checkBox_36.setText("")
        self.checkBox_36.setObjectName("checkBox_36")
        self.gridLayout_3.addWidget(self.checkBox_36, 18, 5, 1, 1)
        self.checkBox_10 = QtWidgets.QCheckBox(self.page)
        self.checkBox_10.setText("")
        self.checkBox_10.setObjectName("checkBox_10")
        self.gridLayout_3.addWidget(self.checkBox_10, 16, 3, 1, 1)
        self.labelResultEx11 = QtWidgets.QLabel(self.page)
        self.labelResultEx11.setObjectName("labelResultEx11")
        self.gridLayout_3.addWidget(self.labelResultEx11, 17, 0, 1, 1)
        self.labelResultEx5 = QtWidgets.QLabel(self.page)
        self.labelResultEx5.setObjectName("labelResultEx5")
        self.gridLayout_3.addWidget(self.labelResultEx5, 11, 0, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem3, 2, 2, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.page)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout_3.addWidget(self.pushButton, 0, 2, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(self.page)
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout_3.addWidget(self.pushButton_2, 0, 3, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout_3, 1, 0, 1, 1)
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.layoutWidget = QtWidgets.QWidget(self.page_2)
        self.layoutWidget.setGeometry(QtCore.QRect(0, 0, 962, 640))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout_6.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.labelResultEx6_2 = QtWidgets.QLabel(self.layoutWidget)
        self.labelResultEx6_2.setObjectName("labelResultEx6_2")
        self.gridLayout_6.addWidget(self.labelResultEx6_2, 7, 0, 1, 1)
        self.labelResultEx11_2 = QtWidgets.QLabel(self.layoutWidget)
        self.labelResultEx11_2.setObjectName("labelResultEx11_2")
        self.gridLayout_6.addWidget(self.labelResultEx11_2, 12, 0, 1, 1)
        self.labelResultEx8_2 = QtWidgets.QLabel(self.layoutWidget)
        self.labelResultEx8_2.setObjectName("labelResultEx8_2")
        self.gridLayout_6.addWidget(self.labelResultEx8_2, 9, 0, 1, 1)
        self.labelResultEx1_2 = QtWidgets.QLabel(self.layoutWidget)
        self.labelResultEx1_2.setObjectName("labelResultEx1_2")
        self.gridLayout_6.addWidget(self.labelResultEx1_2, 1, 0, 1, 1)
        self.spinBox_10 = QtWidgets.QSpinBox(self.layoutWidget)
        self.spinBox_10.setObjectName("spinBox_10")
        self.gridLayout_6.addWidget(self.spinBox_10, 10, 1, 1, 1)
        self.spinBox_12 = QtWidgets.QSpinBox(self.layoutWidget)
        self.spinBox_12.setObjectName("spinBox_12")
        self.gridLayout_6.addWidget(self.spinBox_12, 11, 1, 1, 1)
        self.labelResultEx9_2 = QtWidgets.QLabel(self.layoutWidget)
        self.labelResultEx9_2.setObjectName("labelResultEx9_2")
        self.gridLayout_6.addWidget(self.labelResultEx9_2, 10, 0, 1, 1)
        self.labelResultEx2_2 = QtWidgets.QLabel(self.layoutWidget)
        self.labelResultEx2_2.setObjectName("labelResultEx2_2")
        self.gridLayout_6.addWidget(self.labelResultEx2_2, 2, 0, 1, 1)
        self.spinBox_5 = QtWidgets.QSpinBox(self.layoutWidget)
        self.spinBox_5.setObjectName("spinBox_5")
        self.gridLayout_6.addWidget(self.spinBox_5, 7, 1, 1, 1)
        self.labelResultEx7_2 = QtWidgets.QLabel(self.layoutWidget)
        self.labelResultEx7_2.setObjectName("labelResultEx7_2")
        self.gridLayout_6.addWidget(self.labelResultEx7_2, 8, 0, 1, 1)
        self.spinBox_9 = QtWidgets.QSpinBox(self.layoutWidget)
        self.spinBox_9.setObjectName("spinBox_9")
        self.gridLayout_6.addWidget(self.spinBox_9, 12, 1, 1, 1)
        self.labelResultEx12_2 = QtWidgets.QLabel(self.layoutWidget)
        self.labelResultEx12_2.setObjectName("labelResultEx12_2")
        self.gridLayout_6.addWidget(self.labelResultEx12_2, 13, 0, 1, 1)
        self.spinBox_6 = QtWidgets.QSpinBox(self.layoutWidget)
        self.spinBox_6.setObjectName("spinBox_6")
        self.gridLayout_6.addWidget(self.spinBox_6, 5, 1, 1, 1)
        self.spinBox = QtWidgets.QSpinBox(self.layoutWidget)
        self.spinBox.setObjectName("spinBox")
        self.gridLayout_6.addWidget(self.spinBox, 1, 1, 1, 1)
        self.labelResultEx4_2 = QtWidgets.QLabel(self.layoutWidget)
        self.labelResultEx4_2.setObjectName("labelResultEx4_2")
        self.gridLayout_6.addWidget(self.labelResultEx4_2, 5, 0, 1, 1)
        self.labelResultEx5_2 = QtWidgets.QLabel(self.layoutWidget)
        self.labelResultEx5_2.setObjectName("labelResultEx5_2")
        self.gridLayout_6.addWidget(self.labelResultEx5_2, 6, 0, 1, 1)
        self.labelResultEx3_2 = QtWidgets.QLabel(self.layoutWidget)
        self.labelResultEx3_2.setObjectName("labelResultEx3_2")
        self.gridLayout_6.addWidget(self.labelResultEx3_2, 3, 0, 1, 1)
        self.labelResultEx10_2 = QtWidgets.QLabel(self.layoutWidget)
        self.labelResultEx10_2.setObjectName("labelResultEx10_2")
        self.gridLayout_6.addWidget(self.labelResultEx10_2, 11, 0, 1, 1)
        self.spinBox_4 = QtWidgets.QSpinBox(self.layoutWidget)
        self.spinBox_4.setObjectName("spinBox_4")
        self.gridLayout_6.addWidget(self.spinBox_4, 6, 1, 1, 1)
        self.spinBox_3 = QtWidgets.QSpinBox(self.layoutWidget)
        self.spinBox_3.setObjectName("spinBox_3")
        self.gridLayout_6.addWidget(self.spinBox_3, 3, 1, 1, 1)
        self.spinBox_7 = QtWidgets.QSpinBox(self.layoutWidget)
        self.spinBox_7.setObjectName("spinBox_7")
        self.gridLayout_6.addWidget(self.spinBox_7, 8, 1, 1, 1)
        self.spinBox_8 = QtWidgets.QSpinBox(self.layoutWidget)
        self.spinBox_8.setObjectName("spinBox_8")
        self.gridLayout_6.addWidget(self.spinBox_8, 9, 1, 1, 1)
        self.spinBox_13 = QtWidgets.QSpinBox(self.layoutWidget)
        self.spinBox_13.setObjectName("spinBox_13")
        self.gridLayout_6.addWidget(self.spinBox_13, 13, 1, 1, 1)
        self.spinBox_2 = QtWidgets.QSpinBox(self.layoutWidget)
        self.spinBox_2.setObjectName("spinBox_2")
        self.gridLayout_6.addWidget(self.spinBox_2, 2, 1, 1, 1)
        self.pushButton_3 = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout_6.addWidget(self.pushButton_3, 0, 0, 1, 2)
        self.spinBox_11 = QtWidgets.QSpinBox(self.page_2)
        self.spinBox_11.setGeometry(QtCore.QRect(380, 650, 164, 32))
        self.spinBox_11.setObjectName("spinBox_11")
        self.stackedWidget.addWidget(self.page_2)
        self.verticalLayout.addWidget(self.stackedWidget)
        self.gridLayout_2.addLayout(self.verticalLayout, 0, 0, 1, 1)
        menuWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(menuWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1000, 28))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        self.menuSetting = QtWidgets.QMenu(self.menubar)
        self.menuSetting.setObjectName("menuSetting")
        self.menuWindows = QtWidgets.QMenu(self.menubar)
        self.menuWindows.setObjectName("menuWindows")
        self.menuMove_to_Activity = QtWidgets.QMenu(self.menuWindows)
        self.menuMove_to_Activity.setObjectName("menuMove_to_Activity")
        self.menu_2 = QtWidgets.QMenu(self.menuWindows)
        self.menu_2.setObjectName("menu_2")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        menuWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(menuWindow)
        self.statusbar.setObjectName("statusbar")
        menuWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(menuWindow)
        self.toolBar.setObjectName("toolBar")
        menuWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionAAbout = QtWidgets.QAction(menuWindow)
        self.actionAAbout.setObjectName("actionAAbout")
        self.actionActivity_1 = QtWidgets.QAction(menuWindow)
        self.actionActivity_1.setObjectName("actionActivity_1")
        self.actionActivity_2 = QtWidgets.QAction(menuWindow)
        self.actionActivity_2.setObjectName("actionActivity_2")
        self.actionActivity_3 = QtWidgets.QAction(menuWindow)
        self.actionActivity_3.setObjectName("actionActivity_3")
        self.actionActivity_4 = QtWidgets.QAction(menuWindow)
        self.actionActivity_4.setObjectName("actionActivity_4")
        self.actionActivity_5 = QtWidgets.QAction(menuWindow)
        self.actionActivity_5.setObjectName("actionActivity_5")
        self.actionActivity_6 = QtWidgets.QAction(menuWindow)
        self.actionActivity_6.setObjectName("actionActivity_6")
        self.actionMain_Menu = QtWidgets.QAction(menuWindow)
        self.actionMain_Menu.setObjectName("actionMain_Menu")
        self.actionExport_Data = QtWidgets.QAction(menuWindow)
        self.actionExport_Data.setObjectName("actionExport_Data")
        self.actionMedia_Files_Folder = QtWidgets.QAction(menuWindow)
        self.actionMedia_Files_Folder.setObjectName("actionMedia_Files_Folder")
        self.action6 = QtWidgets.QAction(menuWindow)
        self.action6.setObjectName("action6")
        self.action7 = QtWidgets.QAction(menuWindow)
        self.action7.setObjectName("action7")
        self.action8 = QtWidgets.QAction(menuWindow)
        self.action8.setObjectName("action8")
        self.action9 = QtWidgets.QAction(menuWindow)
        self.action9.setObjectName("action9")
        self.action10 = QtWidgets.QAction(menuWindow)
        self.action10.setObjectName("action10")
        self.action11 = QtWidgets.QAction(menuWindow)
        self.action11.setObjectName("action11")
        self.action12 = QtWidgets.QAction(menuWindow)
        self.action12.setObjectName("action12")
        self.action_2 = QtWidgets.QAction(menuWindow)
        self.action_2.setObjectName("action_2")
        self.action_3 = QtWidgets.QAction(menuWindow)
        self.action_3.setObjectName("action_3")
        self.action_4 = QtWidgets.QAction(menuWindow)
        self.action_4.setObjectName("action_4")
        self.menu.addAction(self.actionExport_Data)
        self.menu.addAction(self.action_4)
        self.menuSetting.addAction(self.actionMedia_Files_Folder)
        self.menuMove_to_Activity.addAction(self.actionActivity_1)
        self.menuMove_to_Activity.addAction(self.actionActivity_2)
        self.menuMove_to_Activity.addAction(self.actionActivity_3)
        self.menuMove_to_Activity.addAction(self.actionActivity_4)
        self.menuMove_to_Activity.addAction(self.actionActivity_5)
        self.menuMove_to_Activity.addAction(self.actionActivity_6)
        self.menuMove_to_Activity.addAction(self.action6)
        self.menuMove_to_Activity.addAction(self.action7)
        self.menuMove_to_Activity.addAction(self.action8)
        self.menuMove_to_Activity.addAction(self.action9)
        self.menuMove_to_Activity.addAction(self.action10)
        self.menuMove_to_Activity.addAction(self.action11)
        self.menuMove_to_Activity.addAction(self.action12)
        self.menu_2.addAction(self.action_2)
        self.menu_2.addAction(self.action_3)
        self.menuWindows.addAction(self.actionMain_Menu)
        self.menuWindows.addAction(self.menu_2.menuAction())
        self.menuWindows.addAction(self.menuMove_to_Activity.menuAction())
        self.menuHelp.addAction(self.actionAAbout)
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menuSetting.menuAction())
        self.menubar.addAction(self.menuWindows.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(menuWindow)
        self.stackedWidget.setCurrentIndex(4)
        QtCore.QMetaObject.connectSlotsByName(menuWindow)

    def retranslateUi(self, menuWindow):
        _translate = QtCore.QCoreApplication.translate
        menuWindow.setWindowTitle(_translate("menuWindow", "Αρχική οθόνη "))
        self.textEdit.setHtml(_translate("menuWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans\'; font-size:14pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'arial,sans-serif\'; font-size:24pt; color:#8ab4f8;\">Εκπαιδευτική εφαρμογή</span></p></body></html>"))
        self.selectExersiceButton.setText(_translate("menuWindow", "Έναρξη"))
        self.clearMenu.setText(_translate("menuWindow", "Εκκαθάριση"))
        self.nameLabel.setText(_translate("menuWindow", "Όνομα"))
        self.saveMenu.setText(_translate("menuWindow", "Αποθήκευση"))
        self.label_2.setText(_translate("menuWindow", "Προσωπικά στοιχεία"))
        self.surnameLabel.setText(_translate("menuWindow", "Επίθετο"))
        self.label.setText(_translate("menuWindow", "Διαθέσιμες επιλογές"))
        self.ageLabel.setText(_translate("menuWindow", "Ηλικία"))
        self.pushButtonMainResults.setText(_translate("menuWindow", "Αποτελέσματα"))
        self.normal.setText(_translate("menuWindow", "Normal"))
        self.label_6.setText(_translate("menuWindow", "Πόσο εύκολος σου φάνηκε ο γρίφος"))
        self.easy.setText(_translate("menuWindow", "Easy"))
        self.terminateButton.setText(_translate("menuWindow", "\n"
"Τερματισμός\n"
""))
        self.feedbackHardButton.setText(_translate("menuWindow", "\n"
"Δύσκολος\n"
""))
        self.nextExersice.setText(_translate("menuWindow", "\n"
"Επόμενη δραστηριότητα\n"
""))
        self.hard.setText(_translate("menuWindow", "Hard"))
        self.feedbackEasyButton.setText(_translate("menuWindow", "\n"
"Εύκολος\n"
""))
        self.feedbackNormalButton.setText(_translate("menuWindow", "\n"
"Έτσι και έτσι\n"
""))
        self.label_11.setText(_translate("menuWindow", "Τέλος"))
        self.go2Home.setText(_translate("menuWindow", "Αρχικό Μενού"))
        self.labelResultEx8.setText(_translate("menuWindow", "Ο Μάξιμος"))
        self.labelResultEx6.setText(_translate("menuWindow", "Τι δείχνουν οι εικόνες"))
        self.label_4.setText(_translate("menuWindow", "Δύσκολος"))
        self.labelResultEx1.setText(_translate("menuWindow", "Το λιοντάρι και τα παπάκια"))
        self.labelResultName.setText(_translate("menuWindow", "Όνομα"))
        self.labelResultSurname.setText(_translate("menuWindow", "Επίθετο"))
        self.labelResultEx12.setText(_translate("menuWindow", "Τι δείχνουν οι εικόνες 2"))
        self.label_8.setText(_translate("menuWindow", "Ημερομηνία"))
        self.label_7.setText(_translate("menuWindow", "Λίστα με αποτελέσματα"))
        self.label_5.setText(_translate("menuWindow", "Έτσι και έτσι"))
        self.labelResultEx7.setText(_translate("menuWindow", "Η μαμά καγκούρο"))
        self.labelResultEx4.setText(_translate("menuWindow", "Η Μαρία και η μαμά της"))
        self.label_3.setText(_translate("menuWindow", "Εύκολος"))
        self.labelResultEx2.setText(_translate("menuWindow", "Ασκηση προσοχής"))
        self.pushButtonResultsNext.setText(_translate("menuWindow", "Επόμενο"))
        self.pushButtoResultPrevius.setText(_translate("menuWindow", "Προηγούμενο"))
        self.labelResultEx10.setText(_translate("menuWindow", "Η Σοφία στο σχολείο"))
        self.labelResultEx3.setText(_translate("menuWindow", "Ο Γιωργάκης και η σοκολάτα"))
        self.labelResultEx9.setText(_translate("menuWindow", "Ο κοκκινός στρατός"))
        self.labelResultEx11.setText(_translate("menuWindow", "Ένα παιγνίδι με γρίφους 2"))
        self.labelResultEx5.setText(_translate("menuWindow", "Ένα παιγνίδι με γρίφους"))
        self.pushButton.setText(_translate("menuWindow", "Αρχική οθόνη"))
        self.pushButton_2.setText(_translate("menuWindow", "Συγκρεντρωτικά"))
        self.labelResultEx6_2.setText(_translate("menuWindow", "Τι δείχνουν οι εικόνες"))
        self.labelResultEx11_2.setText(_translate("menuWindow", "Ένα παιγνίδι με γρίφους 2"))
        self.labelResultEx8_2.setText(_translate("menuWindow", "Ο Μάξιμος"))
        self.labelResultEx1_2.setText(_translate("menuWindow", "Το λιοντάρι και τα παπάκια"))
        self.labelResultEx9_2.setText(_translate("menuWindow", "Ο κοκκινός στρατός"))
        self.labelResultEx2_2.setText(_translate("menuWindow", "Ασκηση προσοχής"))
        self.labelResultEx7_2.setText(_translate("menuWindow", "Η μαμά καγκούρο"))
        self.labelResultEx12_2.setText(_translate("menuWindow", "Τι δείχνουν οι εικόνες 2"))
        self.labelResultEx4_2.setText(_translate("menuWindow", "Η Μαρία και η μαμά της"))
        self.labelResultEx5_2.setText(_translate("menuWindow", "Ένα παιγνίδι με γρίφους"))
        self.labelResultEx3_2.setText(_translate("menuWindow", "Ο Γιωργάκης και η σοκολάτα"))
        self.labelResultEx10_2.setText(_translate("menuWindow", "Η Σοφία στο σχολείο"))
        self.pushButton_3.setText(_translate("menuWindow", "Αρχική οθόνη"))
        self.menu.setTitle(_translate("menuWindow", "Αρχείο"))
        self.menuSetting.setTitle(_translate("menuWindow", "Ρυθμίσεις"))
        self.menuWindows.setTitle(_translate("menuWindow", "Παράθυρο"))
        self.menuMove_to_Activity.setTitle(_translate("menuWindow", "Εφαρμογή"))
        self.menu_2.setTitle(_translate("menuWindow", "Αποτελέσματα"))
        self.menuHelp.setTitle(_translate("menuWindow", "Βοήθεια"))
        self.toolBar.setWindowTitle(_translate("menuWindow", "toolBar"))
        self.actionAAbout.setText(_translate("menuWindow", "About"))
        self.actionActivity_1.setText(_translate("menuWindow", "1"))
        self.actionActivity_2.setText(_translate("menuWindow", "2"))
        self.actionActivity_3.setText(_translate("menuWindow", "3"))
        self.actionActivity_4.setText(_translate("menuWindow", "4"))
        self.actionActivity_5.setText(_translate("menuWindow", "5"))
        self.actionActivity_6.setText(_translate("menuWindow", "6"))
        self.actionMain_Menu.setText(_translate("menuWindow", "Αρχική οθόνη"))
        self.actionExport_Data.setText(_translate("menuWindow", "Εξαγωγή δεδομένων"))
        self.actionMedia_Files_Folder.setText(_translate("menuWindow", "Αρχειο δεδομενων"))
        self.action6.setText(_translate("menuWindow", "6"))
        self.action7.setText(_translate("menuWindow", "7"))
        self.action8.setText(_translate("menuWindow", "8"))
        self.action9.setText(_translate("menuWindow", "9"))
        self.action10.setText(_translate("menuWindow", "10"))
        self.action11.setText(_translate("menuWindow", "11"))
        self.action12.setText(_translate("menuWindow", "12"))
        self.action_2.setText(_translate("menuWindow", "Ατομο"))
        self.action_3.setText(_translate("menuWindow", "Συνολικα"))
        self.action_4.setText(_translate("menuWindow", "Εισαγωγή δεδομένων"))
