# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './resources/page3.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_GroupBox(object):
    def setupUi(self, GroupBox):
        GroupBox.setObjectName("GroupBox")
        GroupBox.resize(955, 613)
        self.layoutWidget = QtWidgets.QWidget(GroupBox)
        self.layoutWidget.setGeometry(QtCore.QRect(12, 15, 771, 481))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout_5.addWidget(self.label_3, 0, 0, 1, 5)
        self.pushButton = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout_5.addWidget(self.pushButton, 1, 1, 1, 1)
        self.answer2 = QtWidgets.QPushButton(self.layoutWidget)
        self.answer2.setObjectName("answer2")
        self.gridLayout_5.addWidget(self.answer2, 6, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.layoutWidget)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout_5.addWidget(self.label_5, 4, 0, 1, 5)
        self.answer1 = QtWidgets.QPushButton(self.layoutWidget)
        self.answer1.setObjectName("answer1")
        self.gridLayout_5.addWidget(self.answer1, 6, 0, 1, 1)
        self.testing = QtWidgets.QWidget(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.testing.sizePolicy().hasHeightForWidth())
        self.testing.setSizePolicy(sizePolicy)
        self.testing.setObjectName("testing")
        self.pushButton_2 = QtWidgets.QPushButton(self.testing)
        self.pushButton_2.setGeometry(QtCore.QRect(220, 100, 89, 25))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.testing)
        self.pushButton_3.setGeometry(QtCore.QRect(110, 70, 89, 25))
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout_5.addWidget(self.testing, 3, 0, 1, 5)
        self.answer4 = QtWidgets.QPushButton(self.layoutWidget)
        self.answer4.setObjectName("answer4")
        self.gridLayout_5.addWidget(self.answer4, 6, 3, 1, 1)
        self.answer3 = QtWidgets.QPushButton(self.layoutWidget)
        self.answer3.setObjectName("answer3")
        self.gridLayout_5.addWidget(self.answer3, 6, 2, 1, 1)
        self.answer5 = QtWidgets.QPushButton(self.layoutWidget)
        self.answer5.setObjectName("answer5")
        self.gridLayout_5.addWidget(self.answer5, 6, 4, 1, 1)
        self.pushButton_4 = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_4.setObjectName("pushButton_4")
        self.gridLayout_5.addWidget(self.pushButton_4, 5, 0, 1, 1)

        self.retranslateUi(GroupBox)
        QtCore.QMetaObject.connectSlotsByName(GroupBox)

    def retranslateUi(self, GroupBox):
        _translate = QtCore.QCoreApplication.translate
        GroupBox.setWindowTitle(_translate("GroupBox", "GroupBox"))
        self.label_3.setText(_translate("GroupBox", "Δραστηριότητα 1"))
        self.pushButton.setText(_translate("GroupBox", "qq"))
        self.answer2.setText(_translate("GroupBox", "B"))
        self.label_5.setText(_translate("GroupBox", "Απαντήσεις"))
        self.answer1.setText(_translate("GroupBox", "A"))
        self.pushButton_2.setText(_translate("GroupBox", "PushButton"))
        self.pushButton_3.setText(_translate("GroupBox", "PushButton"))
        self.answer4.setText(_translate("GroupBox", "Δ"))
        self.answer3.setText(_translate("GroupBox", "Γ"))
        self.answer5.setText(_translate("GroupBox", "Ε"))
        self.pushButton_4.setText(_translate("GroupBox", "PushButton"))
