# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './resources/page1.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1210, 754)
        self.gridLayout_2 = QtWidgets.QGridLayout(Form)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setObjectName("widget")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.widget)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.answer3 = QtWidgets.QPushButton(self.widget)
        self.answer3.setObjectName("answer3")
        self.gridLayout_5.addWidget(self.answer3, 4, 2, 1, 1)
        self.Results = QtWidgets.QLabel(self.widget)
        self.Results.setAlignment(QtCore.Qt.AlignCenter)
        self.Results.setObjectName("Results")
        self.gridLayout_5.addWidget(self.Results, 3, 0, 1, 5)
        self.answer5 = QtWidgets.QPushButton(self.widget)
        self.answer5.setObjectName("answer5")
        self.gridLayout_5.addWidget(self.answer5, 4, 4, 1, 1)
        self.answer2 = QtWidgets.QPushButton(self.widget)
        self.answer2.setObjectName("answer2")
        self.gridLayout_5.addWidget(self.answer2, 4, 1, 1, 1)
        self.name = QtWidgets.QLabel(self.widget)
        self.name.setAlignment(QtCore.Qt.AlignCenter)
        self.name.setObjectName("name")
        self.gridLayout_5.addWidget(self.name, 0, 0, 1, 5)
        self.answer1 = QtWidgets.QPushButton(self.widget)
        self.answer1.setObjectName("answer1")
        self.gridLayout_5.addWidget(self.answer1, 4, 0, 1, 1)
        self.answer4 = QtWidgets.QPushButton(self.widget)
        self.answer4.setObjectName("answer4")
        self.gridLayout_5.addWidget(self.answer4, 4, 3, 1, 1)
        self.mainImage = QtWidgets.QLabel(self.widget)
        self.mainImage.setMaximumSize(QtCore.QSize(800, 600))
        self.mainImage.setScaledContents(True)
        self.mainImage.setObjectName("mainImage")
        self.gridLayout_5.addWidget(self.mainImage, 1, 1, 1, 3, QtCore.Qt.AlignHCenter)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_5.addItem(spacerItem, 1, 0, 1, 1)
        self.gridLayout_2.addWidget(self.widget, 0, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.answer3.setText(_translate("Form", "Γ"))
        self.Results.setText(_translate("Form", "Απαντήσεις"))
        self.answer5.setText(_translate("Form", "Ε"))
        self.answer2.setText(_translate("Form", "B"))
        self.name.setText(_translate("Form", "Δραστηριότητα"))
        self.answer1.setText(_translate("Form", "A"))
        self.answer4.setText(_translate("Form", "Δ"))
        self.mainImage.setText(_translate("Form", "TextLabel"))
