# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './resources/page2.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Frame(object):
    def setupUi(self, Frame):
        Frame.setObjectName("Frame")
        Frame.resize(444, 300)
        self.gridLayout = QtWidgets.QGridLayout(Frame)
        self.gridLayout.setObjectName("gridLayout")
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.answer2 = QtWidgets.QPushButton(Frame)
        self.answer2.setObjectName("answer2")
        self.gridLayout_5.addWidget(self.answer2, 5, 1, 1, 1)
        self.answer3 = QtWidgets.QPushButton(Frame)
        self.answer3.setObjectName("answer3")
        self.gridLayout_5.addWidget(self.answer3, 5, 2, 1, 1)
        self.answer1 = QtWidgets.QPushButton(Frame)
        self.answer1.setObjectName("answer1")
        self.gridLayout_5.addWidget(self.answer1, 5, 0, 1, 1)
        self.answer4 = QtWidgets.QPushButton(Frame)
        self.answer4.setObjectName("answer4")
        self.gridLayout_5.addWidget(self.answer4, 5, 3, 1, 1)
        self.label_5 = QtWidgets.QLabel(Frame)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout_5.addWidget(self.label_5, 4, 0, 1, 5)
        self.testing = QtWidgets.QWidget(Frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.testing.sizePolicy().hasHeightForWidth())
        self.testing.setSizePolicy(sizePolicy)
        self.testing.setObjectName("testing")
        self.gridLayout_5.addWidget(self.testing, 3, 0, 1, 5)
        self.answer5 = QtWidgets.QPushButton(Frame)
        self.answer5.setObjectName("answer5")
        self.gridLayout_5.addWidget(self.answer5, 5, 4, 1, 1)
        self.label_3 = QtWidgets.QLabel(Frame)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout_5.addWidget(self.label_3, 0, 0, 1, 5)
        self.gridLayout.addLayout(self.gridLayout_5, 0, 0, 1, 1)

        self.retranslateUi(Frame)
        QtCore.QMetaObject.connectSlotsByName(Frame)

    def retranslateUi(self, Frame):
        _translate = QtCore.QCoreApplication.translate
        Frame.setWindowTitle(_translate("Frame", "Frame"))
        self.answer2.setText(_translate("Frame", "B"))
        self.answer3.setText(_translate("Frame", "Γ"))
        self.answer1.setText(_translate("Frame", "A"))
        self.answer4.setText(_translate("Frame", "Δ"))
        self.label_5.setText(_translate("Frame", "Απαντήσεις11111"))
        self.answer5.setText(_translate("Frame", "Ε"))
        self.label_3.setText(_translate("Frame", "Δραστηριότητα 111111"))
