# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'views/ui/exb.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore,Qt, QtGui, QtWidgets
from PyQt5.QtGui import * 

class Ui_MainWindow(object):

    def paintEvent(self, event):
        painter = QPainter(self)
        painter.drawPixmap(self.rect(), QPixmap("start.png"))
        MainWindow.paintEvent(self, event)


    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1900, 1200)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(0, 0, 1900, 1200))
        self.widget.setObjectName("widget")
        self.corbiLabel = QtWidgets.QLabel(self.widget)
        self.corbiLabel.setGeometry(QtCore.QRect( 0, 10, 1600, 400))
        self.corbiLabel.setAlignment(QtCore.Qt.AlignHCenter)
        self.corbiLabel.setObjectName("corbiLabel")
        self.statusBar().showMessage("Ready")

        MainWindow.setCentralWidget(self.centralwidget)
        fontId = QFontDatabase.addApplicationFont("fonts/Mansalva.ttf")
        if fontId < 0:
            print('font not loaded')
        else :
            families = QtGui.QFontDatabase.applicationFontFamilies(fontId)
            font = QtGui.QFont(families[0])
            self.widget.setFont(font)
            self.corbiLabel.setFont(font)
        # self.menubar = QtWidgets.QMenuBar(MainWindow)
        # self.menubar.setGeometry(QtCore.QRect(0, 0, 1600, 20))
        # self.menubar.setObjectName("menubar")
        # MainWindow.setMenuBar(self.menubar)
        # self.statusbar = QtWidgets.QStatusBar(MainWindow)
        # self.statusbar.setObjectName("statusbar")
        # MainWindow.setStatusBar(self.statusbar)

       
        # self.centralwidget.setStyleSheet("  { background-image: url(start.png); background-attachment: fixed }")

        
        self.centralwidget.setStyleSheet("#centralwidget{border-image: url(back.png) 0 0 0 0 stretch stretch;} font-family: times; ");

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.corbiLabel.setText(_translate("MainWindow", "corbiLabel"))
        # self.pushButton.setText(_translate("MainWindow", "PushButton"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
