# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'views/ui/exb.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore,Qt, QtGui, QtWidgets
from PyQt5.QtGui import * 

from PyQt5.QtWidgets import (
    QApplication,
    QGridLayout,
    QPushButton,
    QWidget,
)

from PyQt5.QtWidgets import QLabel 

class Ui_MainWindow(object):


    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1920, 1200)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        pixmap = QPixmap("img/back.png")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(0, 0, 1920, 1200))
        self.widget.setObjectName("widget")

        self.label = QLabel(self.widget)
        
        self.corbiLabel = QtWidgets.QLabel(self.widget)
        self.corbiLabel.setGeometry(QtCore.QRect( 0, 0, 1600, 1200))
        self.corbiLabel.setAlignment(QtCore.Qt.AlignHCenter)
        self.corbiLabel.setObjectName("corbiLabel")
 

        MainWindow.setCentralWidget(self.centralwidget)
        fontId = QFontDatabase.addApplicationFont("fonts/Mansalva.ttf")
        if fontId < 0:
            print('font not loaded')
        else :
            families = QtGui.QFontDatabase.applicationFontFamilies(fontId)
            font = QtGui.QFont(families[0])
            self.widget.setFont(font)
            self.corbiLabel.setFont(font)
            self.corbiLabel.setStyleSheet("font-size: 24pt; color : blue; " )
          
      
        self.centralwidget.setStyleSheet("#centralwidget{border-image: url(img/back2.png) 0 0 0 0 stretch stretch;}");
        


        self.label.setPixmap(pixmap)
        self.label.setGeometry(0,0,2000,1800)
        self.label.setScaledContents( True );
        # self.label.ba
        self.label.hide()

        self.wrongIMG = QLabel(self.widget)
        pixmap = QPixmap("img/wrong.png")
        self.wrongIMG.setPixmap(pixmap)
        self.wrongIMG.setScaledContents( True );
        self.wrongIMG.setGeometry(QtCore.QRect(1900/2-200, 1200/2-200, 400, 400))
        self.wrongIMG.hide()

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "LINA: Εκπαιδευτικές δραστηριότητες"))
        self.corbiLabel.setText(_translate("MainWindow", ""))
        # self.pushButton.setText(_translate("MainWindow", "PushButton"))

