# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './resources/menu.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_InsertMenu(object):
    def setupUi(self, InsertMenu):
        InsertMenu.setObjectName("InsertMenu")
        InsertMenu.resize(579, 389)
        self.centralwidget = QtWidgets.QWidget(InsertMenu)
        self.centralwidget.setObjectName("centralwidget")
        self.selectExercise = QtWidgets.QComboBox(self.centralwidget)
        self.selectExercise.setGeometry(QtCore.QRect(20, 260, 241, 21))
        self.selectExercise.setObjectName("selectExercise")
        self.clearMenu = QtWidgets.QPushButton(self.centralwidget)
        self.clearMenu.setGeometry(QtCore.QRect(30, 180, 171, 31))
        self.clearMenu.setObjectName("clearMenu")
        self.name = QtWidgets.QTextEdit(self.centralwidget)
        self.name.setGeometry(QtCore.QRect(160, 30, 211, 21))
        self.name.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.name.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.name.setObjectName("name")
        self.surname = QtWidgets.QTextEdit(self.centralwidget)
        self.surname.setGeometry(QtCore.QRect(160, 70, 211, 21))
        self.surname.setLineWidth(1)
        self.surname.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.surname.setObjectName("surname")
        self.nameLabel = QtWidgets.QLabel(self.centralwidget)
        self.nameLabel.setGeometry(QtCore.QRect(20, 30, 101, 21))
        self.nameLabel.setObjectName("nameLabel")
        self.surnameLabel = QtWidgets.QLabel(self.centralwidget)
        self.surnameLabel.setGeometry(QtCore.QRect(20, 70, 101, 21))
        self.surnameLabel.setObjectName("surnameLabel")
        self.saveMenu = QtWidgets.QPushButton(self.centralwidget)
        self.saveMenu.setGeometry(QtCore.QRect(210, 180, 171, 31))
        self.saveMenu.setObjectName("saveMenu")
        self.selectButton = QtWidgets.QPushButton(self.centralwidget)
        self.selectButton.setGeometry(QtCore.QRect(300, 260, 89, 25))
        self.selectButton.setObjectName("selectButton")
        self.ageTextBox = QtWidgets.QTextEdit(self.centralwidget)
        self.ageTextBox.setGeometry(QtCore.QRect(160, 110, 211, 21))
        self.ageTextBox.setLineWidth(1)
        self.ageTextBox.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.ageTextBox.setObjectName("ageTextBox")
        self.ageLabel = QtWidgets.QLabel(self.centralwidget)
        self.ageLabel.setGeometry(QtCore.QRect(20, 110, 101, 21))
        self.ageLabel.setObjectName("ageLabel")
        InsertMenu.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(InsertMenu)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 579, 22))
        self.menubar.setObjectName("menubar")
        InsertMenu.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(InsertMenu)
        self.statusbar.setObjectName("statusbar")
        InsertMenu.setStatusBar(self.statusbar)

        self.retranslateUi(InsertMenu)
        QtCore.QMetaObject.connectSlotsByName(InsertMenu)

    def retranslateUi(self, InsertMenu):
        _translate = QtCore.QCoreApplication.translate
        InsertMenu.setWindowTitle(_translate("InsertMenu", "MainWindow"))
        self.clearMenu.setText(_translate("InsertMenu", "Εκκαθάριση"))
        self.nameLabel.setText(_translate("InsertMenu", "Όνομα"))
        self.surnameLabel.setText(_translate("InsertMenu", "Επίθετο"))
        self.saveMenu.setText(_translate("InsertMenu", "Αποθήκευση"))
        self.selectButton.setText(_translate("InsertMenu", "Select"))
        self.ageLabel.setText(_translate("InsertMenu", "Ηλικία"))
