# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'resources/menu.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_menuWindow(object):
    def setupUi(self, menuWindow):
        menuWindow.setObjectName("menuWindow")
        menuWindow.resize(826, 541)
        self.centralwidget = QtWidgets.QWidget(menuWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(130, 70, 581, 309))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.saveMenu = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.saveMenu.setObjectName("saveMenu")
        self.gridLayout.addWidget(self.saveMenu, 3, 2, 1, 1)
        self.ageLabel = QtWidgets.QLabel(self.gridLayoutWidget)
        self.ageLabel.setObjectName("ageLabel")
        self.gridLayout.addWidget(self.ageLabel, 2, 0, 1, 1)
        self.selectExersiceButton = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.selectExersiceButton.setObjectName("selectExersiceButton")
        self.gridLayout.addWidget(self.selectExersiceButton, 4, 2, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 3, 1, 1, 1)
        self.nameLabel = QtWidgets.QLabel(self.gridLayoutWidget)
        self.nameLabel.setObjectName("nameLabel")
        self.gridLayout.addWidget(self.nameLabel, 0, 0, 1, 1)
        self.clearMenu = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.clearMenu.setObjectName("clearMenu")
        self.gridLayout.addWidget(self.clearMenu, 3, 0, 1, 1)
        self.selectExercise = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.selectExercise.setObjectName("selectExercise")
        self.gridLayout.addWidget(self.selectExercise, 4, 0, 1, 1)
        self.surnameLabel = QtWidgets.QLabel(self.gridLayoutWidget)
        self.surnameLabel.setObjectName("surnameLabel")
        self.gridLayout.addWidget(self.surnameLabel, 1, 0, 1, 1)
        self.surname = QtWidgets.QTextEdit(self.gridLayoutWidget)
        self.surname.setLineWidth(1)
        self.surname.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.surname.setObjectName("surname")
        self.gridLayout.addWidget(self.surname, 1, 1, 1, 2)
        self.name = QtWidgets.QTextEdit(self.gridLayoutWidget)
        self.name.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.name.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.name.setObjectName("name")
        self.gridLayout.addWidget(self.name, 0, 1, 1, 2)
        self.ageTextBox = QtWidgets.QTextEdit(self.gridLayoutWidget)
        self.ageTextBox.setLineWidth(1)
        self.ageTextBox.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.ageTextBox.setObjectName("ageTextBox")
        self.gridLayout.addWidget(self.ageTextBox, 2, 1, 1, 2)
        menuWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(menuWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 826, 22))
        self.menubar.setObjectName("menubar")
        menuWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(menuWindow)
        self.statusbar.setObjectName("statusbar")
        menuWindow.setStatusBar(self.statusbar)

        self.retranslateUi(menuWindow)
        QtCore.QMetaObject.connectSlotsByName(menuWindow)

    def retranslateUi(self, menuWindow):
        _translate = QtCore.QCoreApplication.translate
        menuWindow.setWindowTitle(_translate("menuWindow", "MainWindow"))
        self.saveMenu.setText(_translate("menuWindow", "Αποθήκευση"))
        self.ageLabel.setText(_translate("menuWindow", "Ηλικία"))
        self.selectExersiceButton.setText(_translate("menuWindow", "Select"))
        self.nameLabel.setText(_translate("menuWindow", "Όνομα"))
        self.clearMenu.setText(_translate("menuWindow", "Εκκαθάριση"))
        self.surnameLabel.setText(_translate("menuWindow", "Επίθετο"))
